Update unfuckcura

diff --git a/sc/unfuckcura b/sc/unfuckcura
--- a/sc/unfuckcura
+++ b/sc/unfuckcura
@@ -1,5 +1,15 @@
 #!/bin/bash
 cd /tmp
-curl -LOJ https://github.com/Ultimaker/Cura/raw/master/requirements.txt
-cat requirements.txt | xargs -n 1 -P $(wc -l requirements.txt | awk '{ print $1 }') pip install
+#add ppa and detect error if ppa failed on that distro
+sudo add-apt-repository ppa:thopiekar/cura-master -y > /dev/null 2>&1
+if ! { sudo apt-get update 2>&1 || echo E: update failed; } | grep -q '^[WE]:'; then
+    echo "Cura PPA successful"
+else
+    echo "Cura PPA or another source failed... removing the Cura PPA to be safe"
+    sudo add-apt-repository --remove ppa:thopiekar/cura-master -y > /dev/null 2>&1
+fi
+
+#install req's
+curl -LOJ https://github.com/Ultimaker/Cura/raw/master/requirements.txt > /dev/null 2>&1
+cat requirements.txt | xargs -n1 -P0 pip3 install
 rm -rf requirements.txt
